// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbdwapunrlnxcuxjhaca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZHdhcHVucmxueGN1eGpoYWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MDMxNjQsImV4cCI6MjA5MDE3OTE2NH0.KTgQ-K3__V_9PWQVEMUGO7XwruxD_Gh0XFr5Jn9IEDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});